---
rbac:
  install: true

Master:
  Image:    jenkins/jenkins
  ImageTag: 2.136
  ServiceType: ClusterIP
  HostName:    jenkins.jobs.do.citopro.com

  Ingress:
    Annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
    TLS:
      - secretName: jenkins-tls
        hosts:
        - jenkins.jobs.do.citopro.com

Persistence:
  Enabled: true
  StorageClass: standard
  Size: 2Gi